// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconGgAdd: typeof import('~icons/gg/add')['default']
  const IconGgBlock: typeof import('~icons/gg/block')['default']
  const IconGgFacebook: typeof import('~icons/gg/facebook')['default']
  const IconGgGoogle: typeof import('~icons/gg/google')['default']
  const IconGgLock: typeof import('~icons/gg/lock')['default']
  const IconGgMail: typeof import('~icons/gg/mail')['default']
  const IconGgSpinner: typeof import('~icons/gg/spinner')['default']
}
export {}
